[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

http://thetapedrive.com/* https://www.thetapedrive.com/:splat 301!
https://thetapedrive.com/* https://www.thetapedrive.com/:splat 301!
