[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "http://thetapedrive.com/*/"
  to = "https://www.thetapedrive.com/p/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "http://thetapedrive.com/"
  to = "https://www.thetapedrive.com/"
  status = 301
  force = true
  
[[redirects]]
  from = "https://thetapedrive.com/"
  to = "https://www.thetapedrive.com/"
  status = 301
  force = true
